/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitProofRouteImport } from './routes/submit-proof'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MyClaimsRouteImport } from './routes/my-claims'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaimIdRouteImport } from './routes/claim.$id'

const SubmitProofRoute = SubmitProofRouteImport.update({
  id: '/submit-proof',
  path: '/submit-proof',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MyClaimsRoute = MyClaimsRouteImport.update({
  id: '/my-claims',
  path: '/my-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimIdRoute = ClaimIdRouteImport.update({
  id: '/claim/$id',
  path: '/claim/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/my-claims': typeof MyClaimsRoute
  '/onboarding': typeof OnboardingRoute
  '/review': typeof ReviewRoute
  '/submit-proof': typeof SubmitProofRoute
  '/claim/$id': typeof ClaimIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/my-claims': typeof MyClaimsRoute
  '/onboarding': typeof OnboardingRoute
  '/review': typeof ReviewRoute
  '/submit-proof': typeof SubmitProofRoute
  '/claim/$id': typeof ClaimIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/my-claims': typeof MyClaimsRoute
  '/onboarding': typeof OnboardingRoute
  '/review': typeof ReviewRoute
  '/submit-proof': typeof SubmitProofRoute
  '/claim/$id': typeof ClaimIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/my-claims'
    | '/onboarding'
    | '/review'
    | '/submit-proof'
    | '/claim/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/my-claims'
    | '/onboarding'
    | '/review'
    | '/submit-proof'
    | '/claim/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/my-claims'
    | '/onboarding'
    | '/review'
    | '/submit-proof'
    | '/claim/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MyClaimsRoute: typeof MyClaimsRoute
  OnboardingRoute: typeof OnboardingRoute
  ReviewRoute: typeof ReviewRoute
  SubmitProofRoute: typeof SubmitProofRoute
  ClaimIdRoute: typeof ClaimIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit-proof': {
      id: '/submit-proof'
      path: '/submit-proof'
      fullPath: '/submit-proof'
      preLoaderRoute: typeof SubmitProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-claims': {
      id: '/my-claims'
      path: '/my-claims'
      fullPath: '/my-claims'
      preLoaderRoute: typeof MyClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$id': {
      id: '/claim/$id'
      path: '/claim/$id'
      fullPath: '/claim/$id'
      preLoaderRoute: typeof ClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MyClaimsRoute: MyClaimsRoute,
  OnboardingRoute: OnboardingRoute,
  ReviewRoute: ReviewRoute,
  SubmitProofRoute: SubmitProofRoute,
  ClaimIdRoute: ClaimIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
